---
- name: playbook for role wireguard
  hosts: all
  become: yes
  
  roles:
    - docker
    - wireguard

  tasks: 

  - name: starting docker-compose wireguard
    community.docker.docker_compose:
      project_src: "/wireguard"
    register: output
  
  - ansible.builtin.debug:
      var: output
  
  - name: Copy config files from remotely host to localy
    ansible.builtin.synchronize:
      src: "{{ item }}"
      dest: "/tmp/{{ ansible_hostname }}/"  
      mode: pull
    with_items:
      - "/wireguard/config/peer*"
