---
- name: playbook for role wireguard
  hosts: all
  become: yes
  
  tasks: 
  - name: Include role wireguard
    include_role:
      name: 'wireguard' 

  - name: starting docker-compose wireguard
    community.docker.docker_compose:
      project_src: "/wireguard"
    register: output
  
  - ansible.builtin.debug:
      var: output


